# Generated by Django 2.2 on 2020-12-13 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation_payment',
            name='razorpay_order_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='consultation_payment',
            name='razorpay_payment_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customersubscribed',
            name='subscribed_expiry',
            field=models.DateField(default=datetime.date(2021, 12, 13)),
        ),
    ]
