# Generated by Django 2.2 on 2020-12-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_auto_20201213_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razorpay_dashboard',
            name='Payment_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='razorpay_dashboard',
            name='booking_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='razorpay_dashboard',
            name='order_id',
            field=models.CharField(max_length=100),
        ),
    ]
