# Generated by Django 2.2 on 2020-12-15 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_auto_20201213_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorviewlog',
            name='subscription_fee',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customersubscribed',
            name='subscribed_expiry',
            field=models.DateField(default=datetime.date(2021, 12, 15)),
        ),
    ]
