# Generated by Django 2.2 on 2020-12-16 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_auto_20201215_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorviewlog',
            name='payment_type',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='customersubscribed',
            name='subscribed_expiry',
            field=models.DateField(default=datetime.date(2021, 12, 16)),
        ),
    ]
