# Generated by Django 2.2 on 2020-12-22 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0005_auto_20201216_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='customersubscribed',
            name='subscribed_expiry',
            field=models.DateField(default=datetime.date(2021, 12, 22)),
        ),
    ]
